# Content for the CallTwin industry landing pages (SEO). Each page is written for how that trade actually gets calls.
# Edit freely, then run: python marketing/build_pages.py

INDUSTRIES = [
  {
    "slug": "plumbers", "name": "Plumbers", "trade": "plumbing", "estimate": True,
    "title": "AI Receptionist for Plumbers | Answer Every Emergency Call 24/7 | CallTwin",
    "h1": "The AI receptionist that answers your plumbing calls while you're under the sink.",
    "lede": "Burst pipes and backed-up drains don't wait for business hours. CallTwin answers every call to your plumbing business, day or night, gets the address and the problem, and texts the job to your phone before the caller hangs up and dials the next plumber.",
    "pains": [
      ("You can't answer with a wrench in your hand", "Most plumbing calls come in while you're on a job. Voicemail loses them: a caller with a leak usually just calls the next number on the list."),
      ("Emergencies come at 2am", "A water heater that lets go at night is your best-paying job of the week, if someone picks up."),
      ("Tire-kickers eat your time", "CallTwin takes the details and the urgency, so you call back the real jobs first."),
    ],
    "call": [("Caller", "Hi, my water heater's leaking all over the basement."), ("CallTwin", "I'm sorry, let's get you taken care of. Is water still coming out right now?"), ("Caller", "Yeah, from the bottom."), ("CallTwin", "If you can, turn the cold supply valve on top of the heater off. What's the address?"), ("CallTwin", "Got it. I'm texting the owner now as an emergency. He'll call you back at the number you're calling from.")],
    "captures": ["Name and callback number, read back and confirmed", "Service address", "What's wrong: leak, clog, no hot water, sewer smell", "Emergency, today, this week or flexible", "Water heater brand and age if they know it"],
    "faq": [
      ("Will it give my prices over the phone?", "No. It never quotes firm prices. It tells callers you'll confirm pricing, which keeps you from getting locked into a number before you see the job."),
      ("Can it handle emergency calls differently?", "Yes. Emergency calls are flagged at the top of the text you get, and callers are told to shut off water or call 911 first when it's a safety issue."),
      ("Do I keep my business number?", "Yes. You forward your existing line to your CallTwin number with *72. Turn it off anytime with *73."),
      ("Can it turn calls into estimates?", "With the AI Estimate add-on, every call becomes a draft estimate priced from your own price book. You approve it and the customer signs and pays a deposit from their phone."),
    ],
  },
  {
    "slug": "hvac", "name": "HVAC Contractors", "trade": "heating and cooling", "estimate": True,
    "title": "AI Receptionist for HVAC Companies | Never Miss a No-Heat Call | CallTwin",
    "h1": "Every no-heat and no-AC call answered, even in peak season.",
    "lede": "The first hot week of summer and the first cold snap of winter bury HVAC shops in calls. CallTwin answers all of them at once, collects the system details and the address, and texts you each job so your techs roll to the right house with the right parts.",
    "pains": [
      ("Peak season overflows your phone", "When 20 people call in an hour, the ones who get voicemail call your competitor."),
      ("Your office closes, the heat doesn't come back", "No-heat calls at night and on weekends are urgent and profitable. CallTwin answers them."),
      ("Callbacks without details waste trips", "You get the system type, age and symptoms before you call back."),
    ],
    "call": [("Caller", "Our furnace stopped working and it's 40 degrees in the house."), ("CallTwin", "I'm sorry, that's no fun. Is it gas or electric, and do you know about how old it is?"), ("Caller", "Gas, maybe 15 years."), ("CallTwin", "Thanks. Is anyone in the home elderly or very young? I'll mark this urgent."), ("CallTwin", "You're all set. The owner has your details and will call you right back.")],
    "captures": ["Name, callback number and address", "No heat, no cooling, noise, leak or maintenance", "Gas, electric, heat pump; brand and age if known", "Urgency and anyone vulnerable in the home", "Best time for a tech to come out"],
    "faq": [
      ("Can it book maintenance visits?", "It takes the request and preferred time and texts it to you. You confirm the slot, so your schedule stays in your hands."),
      ("Does it work for commercial HVAC?", "Yes. Tell it in your settings which work you do and it explains that to callers."),
      ("What if the caller smells gas?", "It tells them to leave the house and call the gas utility or 911 right away, then texts you."),
      ("Can I get estimates out faster?", "The AI Estimate add-on drafts an estimate from each call using your own prices. You review, approve, and the customer signs online."),
    ],
  },
  {
    "slug": "electricians", "name": "Electricians", "trade": "electrical", "estimate": True,
    "title": "AI Receptionist for Electricians | 24/7 Call Answering | CallTwin",
    "h1": "Answer every electrical call without stopping mid-panel.",
    "lede": "You can't pick up the phone with your hands in a live panel. CallTwin answers for you, sorts sparks-and-smoke emergencies from panel upgrade quotes, and texts you every job with the address and details.",
    "pains": [
      ("Calls come in while you're working live", "Stopping to answer is unsafe. Not answering loses the job."),
      ("Big jobs start with a phone call", "Panel upgrades, EV chargers and remodels are worth thousands. Each missed call is a missed quote."),
      ("Safety calls need the right first words", "CallTwin tells callers with burning smells or sparking outlets to call 911 first."),
    ],
    "call": [("Caller", "I want a quote on an EV charger in my garage."), ("CallTwin", "Happy to help. Do you know what size your electrical panel is, like 100 or 200 amps?"), ("Caller", "I think 200."), ("CallTwin", "Great. And roughly how far is the garage from the panel?"), ("CallTwin", "Perfect, I've sent that to the owner. He'll reach out to set up a time to look.")],
    "captures": ["Name, number and address", "Emergency (no power, sparking, burning smell) or project", "Panel size and home age if known", "Project details: EV charger, panel upgrade, lighting, remodel", "Preferred time"],
    "faq": [
      ("Will it try to troubleshoot electrical problems?", "No. It gives basic safety guidance and takes the details. Diagnosis stays with you."),
      ("Can it handle residential and commercial?", "Yes. You tell it what you do in your settings."),
      ("How fast do I get the job?", "The text arrives before the caller has hung up."),
      ("Can it help me quote faster?", "With the AI Estimate add-on, calls become draft estimates priced from your labor rates and price book."),
    ],
  },
  {
    "slug": "roofers", "name": "Roofers", "trade": "roofing", "estimate": True,
    "title": "AI Receptionist for Roofing Companies | Capture Every Storm Lead | CallTwin",
    "h1": "When the storm hits, every roofing call gets answered.",
    "lede": "After a storm your phone rings nonstop and you're on a roof. CallTwin answers every caller, gets the address, the damage and whether they're filing insurance, and texts you each lead so you can schedule inspections in order.",
    "pains": [("Storm surges swamp your line", "Homeowners call three roofers at once. The first one who answers gets the inspection."), ("You're on a roof all day", "You can't answer from a ladder."), ("Insurance jobs need details", "CallTwin asks whether they're filing a claim so you come prepared.")],
    "call": [("Caller", "A tree limb came down on our roof last night."), ("CallTwin", "I'm sorry to hear that. Is water coming inside right now?"), ("Caller", "A little in the attic."), ("CallTwin", "Okay, I'll mark it urgent. Are you planning to file with your insurance?"), ("CallTwin", "Got it. The owner will call you to set up an inspection today.")],
    "captures": ["Name, number and property address", "Leak, storm damage, replacement or repair", "Active water intrusion (urgent)", "Insurance claim yes/no", "Roof type and age if known"],
    "faq": [("Does it schedule inspections?", "It takes the request and best times and texts you. You confirm."), ("Can it handle a flood of calls after a storm?", "Yes. It answers many calls at once."), ("Does it promise insurance coverage?", "Never. It only notes whether they plan to file."), ("Can I send estimates from calls?", "The AI Estimate add-on drafts estimates from your price book for you to review and send.")],
  },
  {
    "slug": "cleaning-services", "name": "Cleaning Services", "trade": "cleaning", "estimate": True,
    "title": "AI Receptionist for Cleaning Businesses | Book More Cleanings | CallTwin",
    "h1": "Turn every cleaning inquiry into a booked quote.",
    "lede": "You and your crew are cleaning when the phone rings. CallTwin answers, asks the size of the home, how often they want service and any special requests, and texts you everything you need to send a quote.",
    "pains": [("Your crew is working when leads call", "Missed inquiries go to the next listing on Google."), ("Quotes need square footage and frequency", "CallTwin asks the right questions every time."), ("Move-out and deep cleans are time-sensitive", "It flags dates so you don't lose the job.")],
    "call": [("Caller", "I need a move-out clean by Friday."), ("CallTwin", "We can help. How many bedrooms and bathrooms?"), ("Caller", "Three and two."), ("CallTwin", "Will the home be empty? And what's the address?"), ("CallTwin", "Thanks, I've sent it over. You'll get a call back with a quote today.")],
    "captures": ["Name, number and address", "Home size: bedrooms, bathrooms, square feet", "Standard, deep, move-in/out, or commercial", "Frequency: one-time, weekly, biweekly, monthly", "Date needed and pets or access notes"],
    "faq": [("Can it quote prices?", "It won't quote firm prices. With the AI Estimate add-on, it drafts a quote from your own price list for you to approve."), ("Can it handle commercial cleaning inquiries?", "Yes. Add it to your services in settings."), ("Does it speak Spanish?", "Yes. If the caller speaks Spanish, it answers in Spanish."), ("What does it cost?", "$500 one-time setup, 14 days free, then $99 a month.")],
  },
  {
    "slug": "landscapers", "name": "Landscapers", "trade": "landscaping", "estimate": True,
    "title": "AI Receptionist for Landscaping Companies | CallTwin",
    "h1": "Landscaping leads answered while you're on the mower.",
    "lede": "Spring and fall bring a wave of calls and you can't hear the phone over the equipment. CallTwin answers every one, gets the property and the work they want, and texts you the lead.",
    "pains": [("You can't hear the phone on a mower", "And voicemail doesn't book jobs."), ("Seasonal rushes are short", "Miss the spring window and the customer signed with someone else."), ("Estimates need property details", "CallTwin asks lot size and scope up front.")],
    "call": [("Caller", "Do you do spring cleanups and weekly mowing?"), ("CallTwin", "Yes, we do. About how big is the property?"), ("Caller", "Maybe half an acre."), ("CallTwin", "Thanks. What's the address, and when would you like to start?"), ("CallTwin", "Got it. The owner will call you with a quote.")],
    "captures": ["Name, number and property address", "Service: mowing, cleanup, mulch, hardscape, snow removal", "Property size", "One-time or recurring", "Start date"],
    "faq": [("Does it work for snow removal in winter?", "Yes. Update your services and it tells callers."), ("Can it take recurring service requests?", "Yes, it notes frequency and start date."), ("Can I send estimates faster?", "The AI Estimate add-on turns calls into estimates from your price list."), ("Do I keep my number?", "Yes. Forward it with *72.")],
  },
  {
    "slug": "contractors", "name": "General Contractors", "trade": "construction and remodeling", "estimate": True,
    "title": "AI Receptionist for Contractors & Remodelers | CallTwin",
    "h1": "Every remodel inquiry answered, qualified and texted to you.",
    "lede": "Remodels and additions start with one phone call, usually while you're on a job site. CallTwin answers, learns the project, the timeline and the budget range, and texts you a qualified lead.",
    "pains": [("Job sites are loud and busy", "You can't take a 10-minute intake call on a ladder."), ("Big projects need qualifying", "CallTwin asks scope, timeline and whether they own the home."), ("Slow follow-up loses bids", "Leads reach you instantly so you call back first.")],
    "call": [("Caller", "We're thinking about redoing our kitchen."), ("CallTwin", "Exciting. Is it a full remodel or updating cabinets and counters?"), ("Caller", "Full remodel."), ("CallTwin", "When are you hoping to start, and do you own the home?"), ("CallTwin", "Great, the owner will call you to set up a walkthrough.")],
    "captures": ["Name, number and address", "Project type and scope", "Timeline", "Homeowner or tenant", "Budget range if they offer it"],
    "faq": [("Will it give ballpark prices?", "No. Pricing stays with you. The AI Estimate add-on drafts estimates from your price book for your approval."), ("Can customers sign estimates online?", "Yes, with the add-on: branded proposal, e-signature and deposit by card."), ("Does it follow up if they don't respond?", "The add-on sends follow-ups at 24 hours, 3 days and 7 days."), ("What does it cost?", "$500 setup, 14 days free, then $99 a month. Estimates add-on is $49 a month.")],
  },
  {
    "slug": "auto-repair", "name": "Auto Repair Shops", "trade": "auto repair", "estimate": True,
    "title": "AI Receptionist for Auto Repair Shops | CallTwin",
    "h1": "Stop losing repair jobs to a ringing phone in the bay.",
    "lede": "Your techs are under cars and the front counter is busy. CallTwin answers every call, gets the year, make, model and what's wrong, and texts it to you so you can book the bay.",
    "pains": [("The counter can't answer every call", "Especially at open and at pickup time."), ("Callers want to know if you can fit them in", "CallTwin takes the details so you can call back with a time."), ("Towed-in and no-start calls are urgent", "They're flagged at the top.")],
    "call": [("Caller", "My check engine light is on and it's shaking."), ("CallTwin", "Sorry to hear it. What's the year, make and model?"), ("Caller", "2016 Honda Accord."), ("CallTwin", "Is it safe to drive, or would you need a tow?"), ("CallTwin", "Okay, I've texted the shop. They'll call to get you in.")],
    "captures": ["Name and number", "Year, make, model and mileage", "Symptoms in the caller's words", "Drivable or needs a tow", "When they can drop it off"],
    "faq": [("Can it quote repair prices?", "No, it tells callers the shop will confirm pricing after looking at the car."), ("Does it work after hours?", "Yes, 24/7."), ("Spanish?", "Yes."), ("Keep my number?", "Yes, forward with *72.")],
  },
  {
    "slug": "salons", "name": "Salons & Barbershops", "trade": "hair and beauty", "estimate": False,
    "title": "AI Receptionist for Salons & Barbershops | CallTwin",
    "h1": "Never miss a booking call while you're behind the chair.",
    "lede": "Your hands are full with a client and the phone won't stop. CallTwin answers, takes the service they want and their preferred time, and texts you the request so you can confirm between clients.",
    "pains": [("You can't answer mid-cut", "And clients hate hearing the phone ring out."), ("Missed calls are missed bookings", "New clients call the next salon."), ("Front desk costs add up", "CallTwin costs less than a few hours of front-desk time a month.")],
    "call": [("Caller", "Do you have anything Saturday for a cut and color?"), ("CallTwin", "Let me take your details. Do you have a preferred stylist?"), ("Caller", "No, anyone's fine."), ("CallTwin", "Morning or afternoon?"), ("CallTwin", "Got it. The salon will text you to confirm a time.")],
    "captures": ["Name and number", "Service: cut, color, braids, nails, shave", "Preferred stylist", "Preferred day and time", "New or returning client"],
    "faq": [("Does it book directly into my calendar?", "It takes the request and texts you; you confirm the time."), ("Can it answer questions about my services?", "Yes, from what you enter in your settings."), ("Spanish?", "Yes."), ("What does it cost?", "$500 setup, 14 days free, then $99 a month.")],
  },
  {
    "slug": "law-firms", "name": "Law Firms", "trade": "legal", "estimate": False,
    "title": "AI Receptionist for Law Firms | 24/7 Legal Intake | CallTwin",
    "h1": "Every potential client call answered and taken down, 24/7.",
    "lede": "People call a lawyer at the worst moment of their week, often after hours. CallTwin answers every call, takes the caller's contact details and a short description of their matter, and texts it to you so you can follow up first.",
    "pains": [("After-hours calls go to competitors", "Accident and arrest calls come at night and on weekends."), ("Intake takes staff time", "CallTwin handles first contact."), ("Speed wins cases", "The first firm to call back usually gets the client.")],
    "call": [("Caller", "I was in a car accident yesterday and need to talk to someone."), ("CallTwin", "I'm sorry. Are you safe and have you gotten medical care if you need it?"), ("Caller", "Yes."), ("CallTwin", "Can I get your name and the best number to reach you? I'll pass this to the attorney right away.")],
    "captures": ["Name and number", "Type of matter in the caller's words", "Date of incident if relevant", "Best time to call back", "How they heard about the firm"],
    "faq": [("Does it give legal advice?", "Never. It only takes contact details and a short description for the attorney."), ("Is it confidential?", "Calls are handled by your own CallTwin line and details go only to you."), ("After hours?", "Yes, 24/7."), ("Spanish?", "Yes.")],
  },
  {
    "slug": "dental-offices", "name": "Dental & Medical Offices", "trade": "dental and medical", "estimate": False,
    "title": "AI Receptionist for Dental & Medical Offices | CallTwin",
    "h1": "Answer every patient call, even when the front desk is slammed.",
    "lede": "When the front desk is checking patients in, the phone rings out. CallTwin picks up overflow and after-hours calls, takes the patient's name, number and reason for calling, and texts your office so staff can call back.",
    "pains": [("Front desk overflow", "New-patient calls that hit voicemail rarely call back."), ("After-hours calls", "Toothaches and urgent questions come at night."), ("Staff time is expensive", "CallTwin handles first contact.")],
    "call": [("Caller", "I'm a new patient and I'd like a cleaning."), ("CallTwin", "Welcome. Can I get your name and best number?"), ("Caller", "Sure."), ("CallTwin", "Do you have dental insurance you'd like the office to check?"), ("CallTwin", "Thanks, the office will call you to schedule.")],
    "captures": ["Name and callback number", "New or existing patient", "Reason for the call", "Insurance carrier if offered", "Best time to call back"],
    "faq": [("Does it give medical advice?", "No. For emergencies it tells callers to call 911."), ("Does it access patient records?", "No. It only takes a message."), ("Overflow only?", "Yes. Forward only when you're busy or after hours, using your carrier's busy or no-answer forwarding."), ("Spanish?", "Yes.")],
  },
  {
    "slug": "real-estate", "name": "Real Estate Agents", "trade": "real estate", "estimate": False,
    "title": "AI Receptionist for Real Estate Agents | Capture Every Buyer & Seller Lead | CallTwin",
    "h1": "Every buyer and seller call answered while you're at a showing.",
    "lede": "Sign calls and listing inquiries come in while you're showing a house. CallTwin answers, finds out whether they're buying or selling, the property or area, and their timeline, and texts you the lead.",
    "pains": [("You're in showings all day", "Sign-call leads go cold in minutes."), ("Qualifying takes time", "CallTwin asks buying or selling, timeline and pre-approval."), ("Nights and weekends are busy", "That's when buyers browse.")],
    "call": [("Caller", "I'm calling about the house on Maple Street."), ("CallTwin", "Great. Are you working with an agent right now?"), ("Caller", "No."), ("CallTwin", "Are you pre-approved, and when are you hoping to move?"), ("CallTwin", "Thanks, the agent will call you to set up a showing.")],
    "captures": ["Name and number", "Buying, selling or renting", "Property or area of interest", "Timeline and pre-approval", "Working with another agent or not"],
    "faq": [("Can it answer questions about a listing?", "Only what you put in your settings. Otherwise it takes a message."), ("24/7?", "Yes."), ("Spanish?", "Yes."), ("Cost?", "$500 setup, 14 days free, then $99 a month.")],
  },
]

CITIES = "Vineland, Millville, Bridgeton, Glassboro, Cherry Hill, Camden, Atlantic City and the rest of South Jersey, Philadelphia and Delaware"
